crafting.shapedBuilder()
    .output(item('minecraft:wooden_sword'))
    .replace()
    .matrix(' P ','hPf',' S ')
    .key('h',ore('toolHammer'))
    .key('f',ore('toolFile'))
    .key('P',ore('plateWood'))
    .key('I',ore('plankWood'))
    .key('S',ore('stickWood'))
    .register()
crafting.shapedBuilder()
    .output(item('minecraft:wooden_shovel'))
    .replace()
    .matrix('hPf',' S ',' S ')
    .key('h',ore('toolHammer'))
    .key('f',ore('toolFile'))
    .key('P',ore('plateWood'))
    .key('I',ore('plankWood'))
    .key('S',ore('stickWood'))
    .register()
crafting.shapedBuilder()
    .output(item('minecraft:wooden_pickaxe'))
    .replace()
    .matrix('PII','hSf',' S ')
    .key('h',ore('toolHammer'))
    .key('f',ore('toolFile'))
    .key('P',ore('plateWood'))
    .key('I',ore('plankWood'))
    .key('S',ore('stickWood'))
    .register()
crafting.shapedBuilder()
    .output(item('minecraft:wooden_axe'))
    .replace()
    .matrix('PIf','PS ','hS ')
    .key('h',ore('toolHammer'))
    .key('f',ore('toolFile'))
    .key('P',ore('plateWood'))
    .key('I',ore('plankWood'))
    .key('S',ore('stickWood'))
    .register()
crafting.shapedBuilder()
    .output(item('minecraft:wooden_hoe'))
    .replace()
    .matrix('PIf','hS ',' S ')
    .key('h',ore('toolHammer'))
    .key('f',ore('toolFile'))
    .key('P',ore('plateWood'))
    .key('I',ore('plankWood'))
    .key('S',ore('stickWood'))
    .register()
crafting.shapedBuilder()
    .output(item('minecraft:stone_sword'))
    .replace()
    .matrix(' P ','hPf',' S ')
    .key('h',ore('toolHammer'))
    .key('f',ore('toolFile'))
    .key('P',ore('plateStone'))
    .key('I',ore('cobblestone'))
    .key('S',ore('stickWood'))
    .register()
crafting.shapedBuilder()
    .output(item('minecraft:stone_shovel'))
    .replace()
    .matrix('hPf',' S ',' S ')
    .key('h',ore('toolHammer'))
    .key('f',ore('toolFile'))
    .key('P',ore('plateStone'))
    .key('I',ore('cobblestone'))
    .key('S',ore('stickWood'))
    .register()
crafting.shapedBuilder()
    .output(item('minecraft:stone_pickaxe'))
    .replace()
    .matrix('PII','hSf',' S ')
    .key('h',ore('toolHammer'))
    .key('f',ore('toolFile'))
    .key('P',ore('plateStone'))
    .key('I',ore('cobblestone'))
    .key('S',ore('stickWood'))
    .register()
crafting.shapedBuilder()
    .output(item('minecraft:stone_axe'))
    .replace()
    .matrix('PIf','PS ','hS ')
    .key('h',ore('toolHammer'))
    .key('f',ore('toolFile'))
    .key('P',ore('plateStone'))
    .key('I',ore('cobblestone'))
    .key('S',ore('stickWood'))
    .register()
crafting.shapedBuilder()
    .output(item('minecraft:stone_hoe'))
    .replace()
    .matrix('PIf','hS ',' S ')
    .key('h',ore('toolHammer'))
    .key('f',ore('toolFile'))
    .key('P',ore('plateStone'))
    .key('I',ore('cobblestone'))
    .key('S',ore('stickWood'))
    .register()